version: "3.8"
services:
    app:
        build: ./app/        
        container_name: app1
        ports:
        - 8000:5000
        links:
        - db 
        networks:
        - python-postgres
        
    db:
        build: ./database/
        container_name: db1
        ports:
        - 5432:5432
        volumes:
         - /var/postgres/data:/var/lib/postgres/data
        networks:
         - python-postgres

networks:
  python-postgres:
       driver : bridge 
       name   : sample 
